// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA0uBBZo4FhdchCVRreJeLR9FFuzz2cTw',
    appId: '1:821628289384:web:abb27b9230cf6b02f696dd',
    messagingSenderId: '821628289384',
    projectId: 'group33-shopping-list-app',
    authDomain: 'group33-shopping-list-app.firebaseapp.com',
    storageBucket: 'group33-shopping-list-app.appspot.com',
    measurementId: 'G-PB53JWDVQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvFWo_m5-y9MIHJhc_mhSOQTjFLz-c66M',
    appId: '1:821628289384:android:164be34a51b27ad5f696dd',
    messagingSenderId: '821628289384',
    projectId: 'group33-shopping-list-app',
    storageBucket: 'group33-shopping-list-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHGf5iuHJTTJXHlWHTrDsmp5Lo1b0Y1KY',
    appId: '1:821628289384:ios:7b56f9a488c4a2eef696dd',
    messagingSenderId: '821628289384',
    projectId: 'group33-shopping-list-app',
    storageBucket: 'group33-shopping-list-app.appspot.com',
    iosBundleId: 'com.example.group33ShoppingListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHGf5iuHJTTJXHlWHTrDsmp5Lo1b0Y1KY',
    appId: '1:821628289384:ios:e9b4cb8c2817a7cdf696dd',
    messagingSenderId: '821628289384',
    projectId: 'group33-shopping-list-app',
    storageBucket: 'group33-shopping-list-app.appspot.com',
    iosBundleId: 'com.example.group33ShoppingListApp.RunnerTests',
  );
}
